#include "global.hpp"

#define SetStr(k, t) case k: { wcscpy(keystr, t); break; }

LPWSTR VirtualKeyCodeText (DWORD code) {
	static wchar_t keystr[20];
	
	switch (code) {
		SetStr(VK_0, L"0");
		SetStr(VK_1, L"1");
		SetStr(VK_2, L"2");
		SetStr(VK_3, L"3");
		SetStr(VK_4, L"4");
		SetStr(VK_5, L"5");
		SetStr(VK_6, L"6");
		SetStr(VK_7, L"7");
		SetStr(VK_8, L"8");
		SetStr(VK_9, L"9");
		SetStr(VK_A, L"A");
		SetStr(VK_B, L"B");
		SetStr(VK_C, L"C");
		SetStr(VK_D, L"D");
		SetStr(VK_E, L"E");
		SetStr(VK_F, L"F");
		SetStr(VK_G, L"G");
		SetStr(VK_H, L"H");
		SetStr(VK_I, L"I");
		SetStr(VK_J, L"J");
		SetStr(VK_K, L"K");
		SetStr(VK_L, L"L");
		SetStr(VK_M, L"M");
		SetStr(VK_N, L"N");
		SetStr(VK_O, L"O");
		SetStr(VK_P, L"P");
		SetStr(VK_Q, L"Q");
		SetStr(VK_R, L"R");
		SetStr(VK_S, L"S");
		SetStr(VK_T, L"T");
		SetStr(VK_U, L"U");
		SetStr(VK_V, L"V");
		SetStr(VK_W, L"W");
		SetStr(VK_X, L"X");
		SetStr(VK_Y, L"Y");
		SetStr(VK_Z, L"Z");
		SetStr(VK_LBUTTON, L"Mouse Left");
		SetStr(VK_RBUTTON, L"Mouse Right");
		SetStr(VK_CANCEL, L"Cancel");
		SetStr(VK_MBUTTON, L"Mouse Middle");
		SetStr(VK_XBUTTON1, L"Mouse X1");
		SetStr(VK_XBUTTON2, L"Mouse X2");
		SetStr(VK_BACK, L"Backspace");
		SetStr(VK_TAB, L"Tab");
		SetStr(VK_CLEAR, L"Clear");
		SetStr(VK_RETURN, L"Enter");
		SetStr(VK_SHIFT, L"Shift");
		SetStr(VK_CONTROL, L"Ctrl");
		SetStr(VK_MENU, L"Alt");
		SetStr(VK_PAUSE, L"Pause");
		SetStr(VK_CAPITAL, L"Caps Lock");
		SetStr(VK_HANGUL, L"Hangul");
		SetStr(VK_IME_ON, L"IME On");
		SetStr(VK_JUNJA, L"Junja");
		SetStr(VK_FINAL, L"IME Final");
		SetStr(VK_HANJA, L"Hanja");
		SetStr(VK_IME_OFF, L"IME off");
		SetStr(VK_ESCAPE, L"Esc");
		SetStr(VK_CONVERT, L"Convert");
		SetStr(VK_NONCONVERT, L"Non Convert");
		SetStr(VK_ACCEPT, L"Accept");
		SetStr(VK_MODECHANGE, L"Mode Change");
		SetStr(VK_SPACE, L"Space Bar");
		SetStr(VK_PRIOR, L"Page Up");
		SetStr(VK_NEXT, L"Page Down");
		SetStr(VK_END, L"End");
		SetStr(VK_HOME, L"Home");
		SetStr(VK_LEFT, L"Left");
		SetStr(VK_UP, L"Up");
		SetStr(VK_RIGHT, L"Right");
		SetStr(VK_DOWN, L"Down");
		SetStr(VK_SELECT, L"Select");
		SetStr(VK_PRINT, L"Print");
		SetStr(VK_EXECUTE, L"Execute");
		SetStr(VK_SNAPSHOT, L"Prt Scrn");
		SetStr(VK_INSERT, L"Insert");
		SetStr(VK_DELETE, L"Delete");
		SetStr(VK_HELP, L"Help");
		SetStr(VK_LWIN, L"Left Window");
		SetStr(VK_RWIN, L"Right Window");
		SetStr(VK_APPS, L"Apps");
		SetStr(VK_SLEEP, L"Sleep");
		SetStr(VK_NUMPAD0, L"Num 0");
		SetStr(VK_NUMPAD1, L"Num 1");
		SetStr(VK_NUMPAD2, L"Num 2");
		SetStr(VK_NUMPAD3, L"Num 3");
		SetStr(VK_NUMPAD4, L"Num 4");
		SetStr(VK_NUMPAD5, L"Num 5");
		SetStr(VK_NUMPAD6, L"Num 6");
		SetStr(VK_NUMPAD7, L"Num 7");
		SetStr(VK_NUMPAD8, L"Num 8");
		SetStr(VK_NUMPAD9, L"Num 9");
		SetStr(VK_MULTIPLY, L"Num *");
		SetStr(VK_ADD, L"Num +");
		SetStr(VK_SEPARATOR, L"Num Separator");
		SetStr(VK_SUBTRACT, L"Num -");
		SetStr(VK_DECIMAL, L"Num .");
		SetStr(VK_DIVIDE, L"Num /");
		SetStr(VK_F1, L"F1");
		SetStr(VK_F2, L"F2");
		SetStr(VK_F3, L"F3");
		SetStr(VK_F4, L"F4");
		SetStr(VK_F5, L"F5");
		SetStr(VK_F6, L"F6");
		SetStr(VK_F7, L"F7");
		SetStr(VK_F8, L"F8");
		SetStr(VK_F9, L"F9");
		SetStr(VK_F10, L"F10");
		SetStr(VK_F11, L"F11");
		SetStr(VK_F12, L"F12");
		SetStr(VK_F13, L"F13");
		SetStr(VK_F14, L"F14");
		SetStr(VK_F15, L"F15");
		SetStr(VK_F16, L"F16");
		SetStr(VK_F17, L"F17");
		SetStr(VK_F18, L"F18");
		SetStr(VK_F19, L"F19");
		SetStr(VK_F20, L"F20");
		SetStr(VK_F21, L"F21");
		SetStr(VK_F22, L"F22");
		SetStr(VK_F23, L"F23");
		SetStr(VK_F24, L"F24");
		SetStr(VK_NUMLOCK, L"Num Lock");
		SetStr(VK_SCROLL, L"Scrl Lock");
		SetStr(VK_LSHIFT, L"Left Shift");
		SetStr(VK_RSHIFT, L"Right Shift");
		SetStr(VK_LCONTROL, L"Left Ctrl");
		SetStr(VK_RCONTROL, L"Right Ctrl");
		SetStr(VK_LMENU, L"Left Alt");
		SetStr(VK_RMENU, L"Right Alt");
		SetStr(VK_BROWSER_BACK, L"Browser Back");
		SetStr(VK_BROWSER_FORWARD, L"Browser Forward");
		SetStr(VK_BROWSER_REFRESH, L"Browser Refresh");
		SetStr(VK_BROWSER_STOP, L"Browser Stop");
		SetStr(VK_BROWSER_SEARCH, L"Browser Search");
		SetStr(VK_BROWSER_FAVORITES, L"Browser Favorites");
		SetStr(VK_BROWSER_HOME, L"Browser Home");
		SetStr(VK_VOLUME_MUTE, L"Volume Mute");
		SetStr(VK_VOLUME_DOWN, L"Volume Down");
		SetStr(VK_VOLUME_UP, L"Volume Up");
		SetStr(VK_MEDIA_NEXT_TRACK, L"Media Next");
		SetStr(VK_MEDIA_PREV_TRACK, L"Media Prev");
		SetStr(VK_MEDIA_STOP, L"Media Stop");
		SetStr(VK_MEDIA_PLAY_PAUSE, L"Media Pause");
		SetStr(VK_LAUNCH_MAIL, L"Launch Mail");
		SetStr(VK_LAUNCH_MEDIA_SELECT, L"Launch Media");
		SetStr(VK_LAUNCH_APP1, L"Launch App1");
		SetStr(VK_LAUNCH_APP2, L"Launch App2");
		SetStr(VK_OEM_1, L";");
		SetStr(VK_OEM_PLUS, L"+");
		SetStr(VK_OEM_COMMA, L",");
		SetStr(VK_OEM_MINUS, L"-");
		SetStr(VK_OEM_PERIOD, L".");
		SetStr(VK_OEM_2, L"/");
		SetStr(VK_OEM_3, L"`");
		SetStr(VK_OEM_4, L"[");
		SetStr(VK_OEM_5, L"\\");
		SetStr(VK_OEM_6, L"]");
		SetStr(VK_OEM_7, L"'");
		SetStr(VK_OEM_8, L"OEM 8");
		SetStr(VK_OEM_102, L"OEM 102");
		SetStr(VK_PROCESSKEY, L"IME Process");
		SetStr(VK_PACKET, L"Packet");
		SetStr(VK_ATTN, L"Attn");
		SetStr(VK_CRSEL, L"CrSel");
		SetStr(VK_EXSEL, L"ExSel");
		SetStr(VK_EREOF, L"ErEOF");
		SetStr(VK_PLAY, L"Play");
		SetStr(VK_ZOOM, L"Zoom");
		SetStr(VK_NONAME, L"NONAME");
		SetStr(VK_PA1, L"PA1");
		SetStr(VK_OEM_CLEAR, L"Clear");
		default: wcscpy(keystr, L"?");
	}
	
	return keystr;
}